version: '3.8'

networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.3.0/24

services:
  nginx:
    image: nginx:1.25-alpine-perl
    container_name: nginx_container
    ports:
      - "5555:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.3.10

  mssql_paises:
    image: leandroexp/imgdbpaises:v1.0
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.3.21

  mssql_idiomas:
    image: leandroexp/imgdbidiomas:v1.0
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.3.22

  arquitectura_server1:
    container_name: arquitectura_server1
    image: leandroexp/serverpaisesidiomas:v1.0
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.3.31

  arquitectura_server2:
    container_name: arquitectura_server2
    image: leandroexp/serverpaisesidiomas:v1.0
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.3.32

  arquitectura_server3:
    container_name: arquitectura_server3
    image: leandroexp/serverpaisesidiomas:v1.0
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.3.33
